version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: anna_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: nutrition_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/init.sql # Инициализация из дампа ради данных по умолчанию

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://anna_user:secretpassword@db:5432/nutrition_db
      PORT: 5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
